name: Publish

on:
  release:
    types: [published]
  push:
    branches:
      - bump-structured-metadata

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.x
            9.x

      - uses: dotnet/nbgv@master
        with:
          setAllVars: true

      - run: echo "NBGV_NuGetPackageVersion $NBGV_NuGetPackageVersion $NBGV_SemVer2"

      - name: pack
        run: dotnet pack ./src/Serilog.Sinks.Loki/Serilog.Sinks.Loki.csproj -c Release -o out --include-symbols --include-source -p:Version=$NBGV_SemVer2

      # - name: publish
      #   run: dotnet nuget push ./out/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ACCESS_TOKEN}} --skip-duplicate
        
      - name: publish-to-github
        run: dotnet nuget push ./out/*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{secrets._GITHUB_TOKEN}} --skip-duplicate
